### ISSUE TITLE
Doesn't work with latest OpenCV

### ISSUE THREAD

**Issue by jbrownkramer** [2sh/StereoscoPy#3]
I like this project.  I used it to make a puzzle for a treasure hunt for my wife.  I see that there has not been any activity for a while, so this may fall on deaf ears.  However, I was working in an environment where OpenCV (4.2.0 I believe) was already installed.  I pip installed StereoscoPy on a Windows machine.  When I first tried to run the script, there was an error in the call to findTransformECC.  It wanted an inputMask and a gaussian blur radius.  I modified the code to pass None and 1 respectively, and it worked.

**Comment by 2sh** [comment]
Oh, nice. How's the project used in the puzzle if you don't mind me asking?
I'm still here. I got a pull request about this a while back but I've been putting it off as I didn't have StereoscoPy installed for testing it and was planning on rewriting sections at some point. Though with this issue as a reminder I thought I'd better just fix it now. Though I'm not sure how it affects the image (I'll check it out during the rewrite), apparently the second parameter's default value is supposed to be 5 so that's what I've used.
Thank you

**Comment by jbrownkramer** [comment]
I made this with it.  Some of the blocks are flat and some stick out.  You use the ones that stick out to get to the next part of the hunt.

![image](https://user-images.githubusercontent.com/4051645/74669942-cc5aa880-516d-11ea-916b-36ebf1a04cee.png)
